# Production Profile Configuration

# Server Configuration for Production
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
  compression:
    enabled: true
    min-response-size: 1024

# Production Elasticsearch Configuration
elasticsearch:
  hosts:
    - name: "primary"
      url: "${ES_PRIMARY_URL:http://uth-es-app-nlb-d4fa226472071754.elb.ap-south-1.amazonaws.com:9200}"
      timeout: 45000
    - name: "secondary"
      url: "${ES_SECONDARY_URL:http://uth-es-app-nlb-d4fa226472071754.elb.ap-south-1.amazonaws.com:9200}"
      timeout: 45000
    - name: "tertiary"
      url: "${ES_TERTIARY_URL:http://uth-es-app3-nlb-81e82784bb8b158a.elb.ap-south-1.amazonaws.com:9200}"
      timeout: 45000
  
  connection:
    pool-size: 20
    keep-alive: true
    socket-timeout: 90000
    connection-timeout: 15000
  
  query:
    default-size: 50
    max-size: 500        # Lower limit for production to prevent memory issues
    timeout: "45s"
    scroll-timeout: "10m"

# Production LLM Configuration
llm:
  provider: "${LLM_PROVIDER:openai}"
  api-key: "${LLM_API_KEY}"
  model: "${LLM_MODEL:gpt-4}"
  timeout: 45000
  max-tokens: 1000
  temperature: 0.1

# Production Logging Configuration
logging:
  level:
    root: WARN
    com.paytm.mcpserver: INFO
    org.elasticsearch: ERROR
    org.springframework.web: WARN
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:logs/elasticsearch-mcp-server.log}
    max-size: 100MB
    max-history: 30

# Production MCP Configuration
mcp:
  server:
    name: "elasticsearch-mcp-server"
    version: "${APP_VERSION:1.0.0}"
    description: "Production Elasticsearch MCP Server"
  
  transport:
    sse:
      endpoint: "/mcp/sse"
      heartbeat-interval: 60000    # Less frequent heartbeat for production
      max-connections: 200         # Higher limit for production

# Production Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
