# Local Development Profile Configuration

# Server Configuration for Local Development
server:
  port: 8080

# Mock Elasticsearch for testing without real cluster
# spring:
#   elasticsearch:
#     mock: true

# Elasticsearch Configuration for Local Development
elasticsearch:
  hosts:
    - name: "primary"
      url: "http://localhost:9200"
      username: ""
      password: ""
      timeout: 30000
  
  connection:
    pool-size: 5
    socket-timeout: 30000
    connection-timeout: 5000

# LLM Configuration for Local Development
llm:
  provider: "openai"
  api-key: "${LLM_API_KEY:demo-key}"
  model: "gpt-3.5-turbo"  # Cheaper model for development
  timeout: 15000
  max-tokens: 500
  temperature: 0.1

# Enhanced Logging for Development
logging:
  level:
    com.paytm.mcpserver: DEBUG
    org.elasticsearch.client: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.SseEmitter: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Development-specific MCP settings
mcp:
  transport:
    sse:
      heartbeat-interval: 10000  # More frequent heartbeat for development
      max-connections: 10        # Lower limit for development
