# Main Application Configuration
spring:
  application:
    name: elasticsearch-mcp-server
  profiles:
    active: local
  
  # CORS & Web Configuration
  webflux:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,OPTIONS
      allowed-headers: "*"
      allow-credentials: false
  
  mvc:
    async:
      request-timeout: 900000  # 15 minutes for long-running SSE connections

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: application/json,text/event-stream

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# Elasticsearch Configuration
elasticsearch:
  hosts:
    - name: "primary"
      url: "http://localhost:9200"
      username: "${ES_USERNAME:}"
      password: "${ES_PASSWORD:}"
      timeout: 900000  # 15 minutes
    - name: "secondary" 
      url: "http://localhost:9201"
      username: "${ES_USERNAME_2:}"
      password: "${ES_PASSWORD_2:}"
      timeout: 900000  # 15 minutes
  
  connection:
    pool-size: 10
    keep-alive: true
    socket-timeout: 900000  # 15 minutes
    connection-timeout: 900000  # 15 minutes
  
  query:
    default-size: 100
    max-size: 1000
    timeout: "15m"  # 15 minutes
    scroll-timeout: "15m"  # 15 minutes

# MCP Server Configuration
mcp:
  server:
    name: "elasticsearch-mcp-server"
    version: "1.0.0"
    description: "Elasticsearch MCP Server with SSE transport"
  
  transport:
    sse:
      endpoint: "/mcp/sse"
      heartbeat-interval: 900000  # 15 minutes
      max-connections: 100
  
  tools:
    enabled:
      - es_search
      - es_schema  
      - es_host_search
      - es_natural_query

# LLM Integration Configuration
llm:
  provider: "openai"
  api-key: "${LLM_API_KEY:}"
  model: "gpt-4"
  timeout: 900000  # 15 minutes
  max-tokens: 1000
  temperature: 0.1

# Logging Configuration
logging:
  level:
    com.paytm.mcpserver: DEBUG
    com.paytm.mcpserver.transport.sse: DEBUG
    org.elasticsearch: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/elasticsearch-mcp-server.log
