# Production Profile Configuration for MCP Client

# Spring Configuration
spring:
  application:
    name: mcp-client-prod

# Server Configuration (different port from MCP server)
server:
  port: 8081
  servlet:
    context-path: /

# Production MCP Server Configuration
mcp:
  server:
    url: "${MCP_SERVER_URL:http://localhost:8080/api/mcp}"
    timeout: 45000  # 45 seconds for production
    retry-attempts: 3
    heartbeat-interval: 60000  # 1 minute

# Redash Configuration for Production ES Queries
redash:
  base-url: "${REDASH_BASE_URL:http://10.84.84.143:5000}"
  api-key: "${REDASH_API_KEY:c2RIBCEnLsSCf27tztPSS3gVtw5fft5TeSxkxfBx}"
  timeout: 30000  # 30 seconds
  poll-interval: 2000  # 2 seconds between polls
  max-poll-attempts: 15  # Max 30 seconds total wait time
  
  datasources:
    primary-id: 3    # UTH_ES_Primary
    secondary-id: 5  # UTH_ES_Secondary  
    tertiary-id: 12  # UTH_ES_Tertiary

# Production Ollama Configuration  
ollama:
  url: "${OLLAMA_URL:http://localhost:11434}"
  model: "${OLLAMA_MODEL:codellama}"
  timeout: 45000  # 45 seconds
  temperature: 0.1
  max-tokens: 1000

# Production Chat Configuration
chat:
  max-history: 50
  session-timeout: 1800000  # 30 minutes
  default-response-size: 100

# Production Logging Configuration
logging:
  level:
    root: WARN
    com.paytm.mcpclient: INFO
    com.paytm.mcpclient.redash: DEBUG  # Detailed logging for Redash integration
    dev.langchain4j: WARN
    okhttp3: WARN
    org.springframework.web: WARN
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE:logs/mcp-client-prod.log}
    max-size: 100MB
    max-history: 30

# Actuator Configuration for Production Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

# Production Environment Variables Documentation
# Set these environment variables for production deployment:
# - REDASH_API_KEY: Your Redash API key for ES query execution
# - REDASH_BASE_URL: Redash server URL (default: http://10.84.84.143:5000)
# - MCP_SERVER_URL: MCP server endpoint URL
# - OLLAMA_URL: Ollama service URL for LLM operations
# - OLLAMA_MODEL: LLM model to use (default: codellama)
# - LOG_FILE: Log file path (default: logs/mcp-client-prod.log)
